"""
Homogenize per-voxel solve_mechanics.py/solve_fracture.py/solve_inelastic.py
field output into a per-timestep table of volume-averaged strain, stress,
von Mises stress, hydrostatic pressure, and (where written) plastic strain /
damage -- see post.homogenize for the actual computation (reusable directly,
e.g. from a notebook) and utils.io.stats for how the result is written.
This script is a thin CLI: parse arguments, call those, print progress.

Output format (``.csv`` or ``.npy``) is picked purely by ``-o/--output``'s
extension, same convention as each solve_*.py script's own ``stats:`` config
key (utils.io.stats.write_stats) -- no separate --format flag to keep in
sync with the filename. Default is ``<stem>_homogenized.csv``.

Usage
-----
    python scripts/postprocessing/homogenize.py output/simulation/<jobname>
    python scripts/postprocessing/homogenize.py output/simulation/<jobname>.h5 -o results.csv
    python scripts/postprocessing/homogenize.py output/simulation/<jobname> -o results.npy

Output
------
    <stem>_homogenized.csv (or .npy with -o ...npy) -- one row per timestep:
        step, [t|gamma], [converged],
        eps_11, eps_22, eps_33, eps_12, eps_13, eps_23,
        sigma_11, sigma_22, sigma_33, sigma_12, sigma_13, sigma_23,
        mises_stress, pressure,
        [plastic_strain_mean, plastic_strain_max],
        [eps_p_11, eps_p_22, eps_p_33, eps_p_12, eps_p_13, eps_p_23,
         plastic_vol_strain],
        [damage_mean, damage_max]
    The .csv carries a ``#``-prefixed job-metadata banner above the header
    (job provenance, grid, materials) -- read it back with
    scripts/postprocessing/plot_homogenized.py, or any CSV reader that
    supports a comment prefix, e.g. ``pandas.read_csv(path, comment="#")``;
    plain ``numpy.genfromtxt(..., comments="#")`` mis-splits the metadata
    lines that embed commas (a material's ``repr()``), see
    plot_homogenized.py's own loader for a workaround. The .npy has no
    such banner (a structured array can't carry free text) -- just
    ``np.load(path)``.
"""

import argparse
import sys
from pathlib import Path
from typing import cast

import h5py

sys.path.insert(0, "src")

from post.homogenize import find_stats_path, homogenized_table, load_stats  # noqa: E402
from utils.io.stats import write_stats  # noqa: E402


def _stem(job: Path) -> Path:
    """Strip a known suffix (.h5 / _stats.npy / _stats.csv / .xdmf) off a job path, if present."""
    s = str(job)
    for suffix in ("_stats.npy", "_stats.csv", ".h5", ".xdmf"):
        if s.endswith(suffix):
            return Path(s[: -len(suffix)])
    return job


def _metadata_comment(h5_path: Path, field_names: tuple[str, ...]) -> str:
    """Free-text banner for write_stats(..., comment=...): job provenance,
    grid, materials, and notation notes for a couple of nontrivial columns --
    CSV-only (see write_stats), so this only ever gets used for that format."""
    with h5py.File(h5_path, "r") as f:
        attrs = dict(f.attrs)

    lines = [f"Homogenized (volume-averaged) response, generated by "
             f"scripts/postprocessing/homogenize.py from {h5_path}"]
    if "input" in attrs:
        lines.append(f"input: {attrs['input']}")
    # cast: h5py's stubs type an attribute value as (possibly) h5py.Empty
    # (the placeholder for an empty-dataspace attribute, never actually
    # written here) alongside the real array, so a type checker sees Empty
    # -- which has no __iter__ -- as a possibility; the solve_*.py writers
    # always store these as real numeric/object-dtype arrays.
    if "n" in attrs and "L" in attrs:
        lines.append(f"grid n: {tuple(int(v) for v in cast(list, attrs['n']))}   "
                      f"L: {tuple(float(v) for v in cast(list, attrs['L']))}")
    if "material_repr" in attrs:
        for m in cast(list, attrs["material_repr"]):
            lines.append(f"material: {m}")
    lines.append("pressure = tr(sigma_bar)/3, p > 0 = hydrostatic tension")
    if "eps_p" in field_names:
        lines.append("plastic_strain_* = scalar hardening variable alpha; eps_p_* = plastic "
                      "strain tensor (Voigt); plastic_vol_strain = tr(eps_p_bar) = plastic "
                      "volume change")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Homogenize per-voxel solve_mechanics.py/solve_fracture.py/"
                    "solve_inelastic.py field output into a per-timestep table of "
                    "volume-averaged strain, stress, von Mises stress, hydrostatic "
                    "pressure, and (where written) plastic strain / damage."
    )
    parser.add_argument("job", type=Path,
                        help="<stem>.h5, <stem>_stats.npy/.csv, or the bare <stem> "
                             "written by one of the solve_*.py scripts")
    parser.add_argument("-o", "--output", type=Path, default=None,
                        help="Output path, .csv or .npy (default: <stem>_homogenized.csv); "
                             "the extension picks the format")
    args = parser.parse_args()

    stem = _stem(args.job)
    h5_path = Path(str(stem) + ".h5")
    if not h5_path.exists():
        raise FileNotFoundError(f"{h5_path} not found")
    stats_path = find_stats_path(stem)

    stats = load_stats(stats_path)
    if stats is None:
        print(f"Note: {stats_path} not found (or has no 'step' field) -- "
              f"output will have no t/gamma/converged columns.")

    dtype, rows = homogenized_table(h5_path, stats)

    out_path = args.output if args.output else Path(str(stem) + "_homogenized.csv")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    # cast: dtype.names is typed tuple[str, ...] | None (None only for a
    # non-structured dtype) -- homogenized_table always returns a structured
    # one, so it's never actually None here.
    field_names = cast(tuple, dtype.names)
    comment = _metadata_comment(h5_path, field_names) if out_path.suffix == ".csv" else None
    write_stats(out_path, dtype, rows, comment=comment)

    print(f"Read   ← {h5_path}   ({len(rows)} timesteps)")
    print(f"Written → {out_path}")
    print(f"columns: {dtype.names}")


if __name__ == "__main__":
    main()
